apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-data
  namespace: log
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
      role: data
  template:
    metadata:
      labels:
        app: elasticsearch
        role: data
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.3
        ports:
        - containerPort: 9200
          protocol: TCP
        - containerPort: 9300
          protocol: TCP
#        volumeMounts:
#        - name: data
#          mountPath: /usr/share/elasticsearch/data
        env:
          - name: "cluster.name"
            value: "elasticsearch-cluster"
          - name: "discovery.zen.ping.unicast.hosts"
            value: "elasticsearch-discovery"
          - name: "node.master"
            value: "false"
          - name: "node.data"
            value: "true"
          - name: "ES_JAVA_OPTS"
            value: "-Xms256m -Xmx256m"
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
#  volumeClaimTemplates:
#  - metadata:
#      name: data
#      namespace: log
#    spec:
#      accessModes: [ "ReadWriteOnce" ]
#      storageClassName: nfs
#      resources:
#        requests:
#          storage: 10Gi