apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: log
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:6.4.3
        env:
          - name: ELASTICSEARCH_HOSTS
            value: http://elasticsearch-data.log.svc.cluster.local:9200
          - name: SERVER_NAME
            value: kibana
        ports:
        - containerPort: 5601
          name: dashboard
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /api/status
            port: ui
          initialDelaySeconds: 5
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/status
            port: ui
          initialDelaySeconds: 5
          timeoutSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: kibana
  name: kibana
  namespace: log
spec:
  ports:
    - port: 5601
      targetPort: 5601
  selector:
    app: kibana
  type: NodePort